/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "calculator-test.check" instead.
 */

#include <check.h>

#line 1 "calculator-test.check"
/* 
Roman calculator: performs addition and subtraction of roman values
Author: Vinay vittal Karagod
File dependents: main.c, calculator.h, calculator.c,calculator-test.check
Date: 09/03/2016
calculator-test.check: Test file used to pass the input values to calculate roman numbers.
*/


# include "calculator.h"

START_TEST(calc)
{
#line 13

//ck_assert_msg(strcmp(calculate("II","II"),'1') == 0,"operation failed");
ck_assert_msg(calculate("III") == 3,"operation failed");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, calc);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
